sonar.projectKey=projeto-crm-2026
sonar.projectName=crm-services
sonar.sources=.
sonar.exclusions=**/*.test.go,**/*_test.go, **/*.pb.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go