sonar.projectKey=atoken-contemplated-quotas
sonar.projectName=atoken-contemplated-quotas
sonar.sources=.
sonar.exclusions=**/*.test.go,**/*_test.go, **/*.pb.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go